# Generated by Django 4.2.3 on 2023-08-09 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_studentmodel_alter_student_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
